kind: Deployment
apiVersion: apps/v1
metadata:
   name: diamond-prediction
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: diamond-prediction
   template:
      metadata:
        labels:
          app: diamond-prediction
      spec:
       containers:
        - name: diamond-prediction
          image: sarthakvajpayee/pipeline_diamond
          imagePullPolicy: Always
          ports:
          - containerPort: 80
