kind: Service                             
apiVersion: v1
metadata:
  name: diamond_prediction
  labels:
    app: diamond_prediction
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: diamond_prediction          
  type: LoadBalancer                   
