kind: Service                             
apiVersion: v1
metadata:
  name: diamond-prediction
  labels:
    app: diamond-prediction
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: diamond-prediction          
  type: LoadBalancer                   
