kind: Service                             
apiVersion: v1
metadata:
  name: diamond-prediction
  labels:
    app: diamond-prediction
spec:
  ports:
    - port: 80                               
      targetPort: 8501                    
      nodePort: 31200
  selector:
    app: diamond-prediction          
  type: LoadBalancer
